### ISSUE TITLE
Add coauthors

### ISSUE THREAD

**Issue by dhimmel** [greenelab/connectivity-search-manuscript#23]
Currently, the author section looks [like](https://greenelab.github.io/connectivity-search-manuscript/v/5d0aeaef30b20ffc14a0ce0db12bcb173525d240/#authors):

![image](https://user-images.githubusercontent.com/1117703/103160875-edd1eb00-47a7-11eb-8c5e-45b51cd21911.png)

While the manuscript is still not complete, I think it makes sense to begin adding all coauthors.

@cgreene and I last discussed authorship in June 2020. But from my [notes](https://greenelab.slack.com/archives/D0EPLQFHT/p1592849474003000), we had sketched out the following author ordering:

> Himmelstein, Zietz, Rubinetti, Kloster, Heil, Hu, Nicholson, Hao, Sullivan, Nagle, Greene

A few notes:

- this order is of course preliminary as the manuscript is not complete
- we will reorder authors as warranted by additional contributions
- let us know if we could be forgetting someone
- from the greenelab [onboarding](https://github.com/greenelab/onboarding/blob/a11e024e2fc37a07c38a10945f5905ea8a5b373e/onboarding.md)
    > Our lab follows the [Perelman School of Medicine Authorship Policy](https://www.med.upenn.edu/policy/user_documents/2_Announcement_MemoLJLRE_PerelmanSchoolofMedicineAuthorshipPolicy.pdf). These guidelines are derived from ICMJE's Uniform Requirements for Manuscripts Submitted to Biomedical Journals."
- we feel everyone listed above meets the criteria for authorship. But if for any reason someone would not like to be a coauthor, let us know either here or privately.
- we'll notify everyone when the manuscript is complete, by commenting on this issue or elsewhere, before making the initial release (e.g. preprint or journal submission).

In the next comment, I will tag people and provide instructions for adding yourself as a coauthor.

**Comment by dhimmel** [comment]
To add your authorship information, go to https://github.com/greenelab/connectivity-search-manuscript/edit/main/content/metadata.yaml and add the following (replacing my information with your information):

```yaml
  - github: dhimmel
    name: Daniel S. Himmelstein
    initials: DSH
    orcid: 0000-0002-3012-7446
    twitter: dhimmel
    email: daniel.himmelstein@gmail.com
    affiliations:
      - Department of Systems Pharmacology and Translational Therapeutics, University of Pennsylvania, Philadelphia, Pennsylvania, United States of America
      - Related Sciences
    funders: GBMF4552
```

If you don't have a specific piece of metadata, delete it (for example delete twitter line if you don't want to display a twitter account). For funders, put only funders that supported your work on this study.

Then make a pull request on GitHub.
